development:
    searchUrl: 'https://api.twitter.com/'
    searchPath: '/1/users/show.json?screen_name=**USERNAME**&include_entities=true'
    timelinePath: '/1/statuses/user_timeline.json?include_entities=true&include_rts=true&screen_name=**USERNAME**&count=1000'

test:
    searchUrl: 'https://api.twitter.com/1/users/show.json?screen_name=**USERNAME**&include_entities=true'
    searchPath: '/1/users/show.json?screen_name=**USERNAME**&include_entities=true'
    timelinePath: '/1/statuses/user_timeline.json?include_entities=true&include_rts=true&screen_name=**USERNAME**&count=1000'

production:
    searchUrl: 'https://api.twitter.com/1/users/show.json?screen_name=**USERNAME**&include_entities=true'
    searchPath: '/1/users/show.json?screen_name=**USERNAME**&include_entities=true'
    timelinePath: '/1/statuses/user_timeline.json?include_entities=true&include_rts=true&screen_name=**USERNAME**&count=1000'